#!/bin/bash

help() {
    echo "./fuzzer [options]"
    echo "       - --install"
    echo "       - binary_name input_name"
    echo "       - --test <directory containing a list of binaries and sample input for them>"
}

install() {
    sudo apt update
    sudo apt install software-properties-common
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt update
    sudo apt install python3.10
    python3 -m pip install -r requirements.txt
}

if [ $1 = "--install" ]; then
    install;
elif [ $1 = "--help" ]; then
    help;
elif [ $1 = "--test" ] && [ -d $2 ]; then
    [ -d $2 ] && echo "asd"
    for sample in $2/*.txt; do
        binary=$(echo $sample | sed 's/\.txt//i')
        echo $binary $sample
        python3 -m fuzzball $binary $sample;
    done
elif [ $# = 2 ] && ! [[ $1 =~ ^-- ]]; then
    python3 -m fuzzball "$@";
else
    help;
fi
