#!/bin/bash

help() {
    echo "./fuzzer [options]"
    echo "       - install"
    echo "       - [--test] binary_name input_name"
}

if [ $1 = "--install" ]; then
    sudo apt update
    sudo apt install software-properties-common
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt update
    sudo apt install python3.10
    # python -m pip install -r requirements.txt
elif [ $1 = "--help" ]; then
    help;
elif [ $1 = "--test" ]; then
    # test a number of different binaries at once
elif [ $# = 2 ]; then
    python3 -m fuzzball "$@"
else; then
    help;
fi
