#!/bin/bash

help() {
    echo "./fuzzer [options]"
    echo "       - --install"
    echo "       - binary_name input_name"
    echo "       - --test"
    echo "       - --test <directory containing binaries and their sample input>"
}

install() {
    sudo apt update
    sudo apt install software-properties-common
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt update
    sudo apt install python3.10
    python3 -m pip install -r requirements.txt
}

run_test() {
    python3 -m fuzzball $1 $2;
}

run_tests() {
    for sample in $1/*.txt; do
        binary=$(echo $sample | sed 's/\.txt//i')
        run_test binary sample
    done
}

if [ $1 = "--install" ]; then
    install;
elif [ $1 = "--help" ]; then
    help;
elif [ $1 = "--test" ] && [ $# = 1 ]
    run_tests fuzzball/tests/binaries
elif [ $1 = "--test" ] && [ -d $2 ]; then
    run_tests $2
elif [ $# = 2 ] && ! [[ $1 =~ ^-- ]]; then
    run_test "$@";
else
    help;
fi
